#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

VERSION=$(python "$NEBULA_DIR/dialogs.py" list \
"CD DOS Version (English UK), \
Floppy DOS Version (English UK), \
CD DOS Version (English US), \
CD DOS Version (French), \
CD DOS Version (German), \
CD DOS Version (Italian), \
CD DOS Version (Spanish)"
)

if [ "$VERSION" == "CD DOS Version (English UK)" ]; then
LANG="uk"
if [ ! -f "$DOWNLOAD_DIR/$GAME_NAME/dreamweb-cd-uk-1.1.zip" ]; then
get_mylib_distr 'dreamweb-cd-uk-1.1.zip' \
'http://scummvm.org/frs/extras/Dreamweb/dreamweb-cd-uk-1.1.zip'
fi
fi

if [ "$VERSION" == "Floppy DOS Version (English UK)" ]; then
LANG="uk"
if [ ! -f "$DOWNLOAD_DIR/$GAME_NAME/dreamweb-uk-1.1.zip" ]; then
get_mylib_distr 'dreamweb-uk-1.1.zip' \
'http://scummvm.org/frs/extras/Dreamweb/dreamweb-uk-1.1.zip'
fi
fi

if [ "$VERSION" == "CD DOS Version (English US)" ]; then
LANG="us"
if [ ! -f "$DOWNLOAD_DIR/$GAME_NAME/dreamweb-cd-us-1.1.zip" ]; then
get_mylib_distr 'dreamweb-cd-us-1.1.zip' \
'http://scummvm.org/frs/extras/Dreamweb/dreamweb-cd-us-1.1.zip'
fi
fi

if [ "$VERSION" == "CD DOS Version (French)" ]; then
LANG="fr"
if [ ! -f "$DOWNLOAD_DIR/$GAME_NAME/dreamweb-cd-fr-1.1.zip" ]; then
get_mylib_distr 'dreamweb-cd-fr-1.1.zip' \
'http://scummvm.org/frs/extras/Dreamweb/dreamweb-cd-fr-1.1.zip'
fi
fi

if [ "$VERSION" == "CD DOS Version (German)" ]; then
LANG="de"
if [ ! -f "$DOWNLOAD_DIR/$GAME_NAME/dreamweb-cd-de-1.1.zip" ]; then
get_mylib_distr 'dreamweb-cd-de-1.1.zip' \
'http://scummvm.org/frs/extras/Dreamweb/dreamweb-cd-de-1.1.zip'
fi
fi

if [ "$VERSION" == "CD DOS Version (Italian)" ]; then
LANG="it"
if [ ! -f "$DOWNLOAD_DIR/$GAME_NAME/dreamweb-cd-it-1.1.zip" ]; then
get_mylib_distr 'dreamweb-cd-it-1.1.zip' \
'http://scummvm.org/frs/extras/Dreamweb/dreamweb-cd-it-1.1.zip'
fi
fi

if [ "$VERSION" == "CD DOS Version (Spanish)" ]; then
LANG="es"
if [ ! -f "$DOWNLOAD_DIR/$GAME_NAME/dreamweb-cd-es-1.1.zip" ]; then
get_mylib_distr 'dreamweb-cd-es-1.1.zip' \
'http://scummvm.org/frs/extras/Dreamweb/dreamweb-cd-es-1.1.zip'
fi
fi

if [ "$LANG" == "uk" ]; then
if [ "$VERSION" == "CD DOS Version (English UK)" ]; then
ARCHIVE="$DOWNLOAD_DIR/$GAME_NAME/dreamweb-cd-uk-1.1.zip"
fi
if [ "$VERSION" == "Floppy DOS Version (English UK)" ]; then
ARCHIVE="$DOWNLOAD_DIR/$GAME_NAME/dreamweb-uk-1.1.zip"
fi
else
ARCHIVE="$DOWNLOAD_DIR/$GAME_NAME/dreamweb-cd-$LANG-1.1.zip"
fi

7z x -aoa -o"$INSTALL_DIR/$GAME_NAME/game" "$ARCHIVE" \
& proc_timer $! "Extracting archive"

if [ "$KEEP_INSTALLERS" == 'False' ]; then
rm -R "$DOWNLOAD_DIR/$GAME_NAME"
fi

if [ "$LANG" == "uk" ]; then

echo -e '#!/bin/bash
python "$NEBULA_DIR/launcher_scummvm.py" dreamweb dreamweb' > \
"$START_FILE" && chmod +x "$START_FILE"

echo -e "[dreamweb]
gameid=dreamweb" > "$INSTALL_DIR/$GAME_NAME/scummvmrc"

else

echo -e '#!/bin/bash
python "$NEBULA_DIR/launcher_scummvm.py" dreamweb '"dreamweb-cd-$LANG" > \
"$START_FILE" && chmod +x "$START_FILE"

echo -e "[dreamweb-cd-$LANG]
gameid=dreamweb
language=$LANG" > "$INSTALL_DIR/$GAME_NAME/scummvmrc"

fi

#DreamWeb
