#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

ARCH=$(get_arch i)

VERSION=$(python "$NEBULA_DIR/dialogs.py" list "With music, Without music")

if [ "$VERSION" == "With music" ]; then
if [ "$ARCH" == "amd64" ]; then
ARCHIVE='t-engine4-linux64-1.5.0.tar.bz2'
else
ARCHIVE='t-engine4-linux32-1.5.0.tar.bz2'
fi
else
if [ "$ARCH" == "amd64" ]; then
ARCHIVE='t-engine4-linux64-1.5.0-nomusic.tar.bz2'
else
ARCHIVE='t-engine4-linux32-1.5.0-nomusic.tar.bz2'
fi
fi

get_mylib_distr "$ARCHIVE" \
"http://te4.org/dl/t-engine/$ARCHIVE"

mkdir -p "$INSTALL_DIR/$GAME_NAME/game"
tar --strip-components=1 -xjvf "$DOWNLOAD_DIR/$GAME_NAME/$ARCHIVE" -C "$INSTALL_DIR/tome/game" \
& proc_timer $! "Extracting $ARCHIVE"

if [ "$KEEP_INSTALLERS" == 'False' ]; then
rm -R "$DOWNLOAD_DIR/$GAME_NAME"
fi

echo -e '#!/bin/bash
cd "$INSTALL_DIR/tome/game"
./t-engine' > "$START_GN_FILE" && chmod +x "$START_GN_FILE"

#Tales of Maj'Eyal
