#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

get_mylib_distr 'The_Lost_Vikings.zip' \
'http://dist.blizzard.com/downloads/classics/9f8ba2a406416a70cfe1bc97ec5346ba/The_Lost_Vikings.zip'

7z x -aoa -o"$INSTALL_DIR/$GAME_NAME/tmp" "$DOWNLOAD_DIR/$GAME_NAME/The_Lost_Vikings.zip"
mv "$INSTALL_DIR/$GAME_NAME/tmp/The Lost Vikings/VIKINGS" "$INSTALL_DIR/$GAME_NAME/game"
rm -R "$INSTALL_DIR/$GAME_NAME/tmp"

if [ "$KEEP_INSTALLERS" == 'False' ]; then
rm -R "$DOWNLOAD_DIR/$GAME_NAME"
fi

#The Lost Vikings
