#!/bin/bash

DOWNLOAD_DIR=$1
INSTALL_DIR=$2
KEEP_INSTALLERS=$4

if [ ! -e $DOWNLOAD_DIR'/the_lost_vikings' ]; then
	mkdir -p $DOWNLOAD_DIR'/the_lost_vikings'
	curl -L -o $DOWNLOAD_DIR'/the_lost_vikings/The_Lost_Vikings.zip' \
	'http://dist.blizzard.com/downloads/classics/9f8ba2a406416a70cfe1bc97ec5346ba/The_Lost_Vikings.zip'

fi

mkdir -p $INSTALL_DIR/'the_lost_vikings/tmp'
unzip $DOWNLOAD_DIR'/the_lost_vikings/The_Lost_Vikings.zip' \
-d $INSTALL_DIR/'the_lost_vikings/tmp'
mv $INSTALL_DIR/'the_lost_vikings/tmp/The Lost Vikings/VIKINGS' \
$INSTALL_DIR/'the_lost_vikings/game'
rm -R $INSTALL_DIR/'the_lost_vikings/tmp'

if [ $KEEP_INSTALLERS == 'False' ]; then
	rm -R $DOWNLOAD_DIR'/the_lost_vikings'
fi

echo '#!/bin/bash
INSTALL_DIR=$1
NEBULA_DIR=$2
rm $HOME/.games_nebula/games/.dosbox/the_lost_vikings
mkdir -p $HOME/.games_nebula/games/.dosbox
ln -s $INSTALL_DIR/the_lost_vikings/game \
$HOME/.games_nebula/games/.dosbox/the_lost_vikings
python $NEBULA_DIR/launcher_dosbox.py the_lost_vikings' > \
$INSTALL_DIR'/the_lost_vikings/start.sh'
chmod +x $INSTALL_DIR'/the_lost_vikings/start.sh'

echo "[autoexec]
@echo off
mount C $HOME/.games_nebula/games/.dosbox/the_lost_vikings
c:
cls
VIKINGS.EXE
exit" > $INSTALL_DIR'/the_lost_vikings/dosbox_game.conf'

#The Lost Vikings
