#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

get_mylib_distr 'soltys-en-v1.0.zip' \
'http://scummvm.org/frs/extras/Soltys/soltys-en-v1.0.zip'

7z x -o"$INSTALL_DIR/$GAME_NAME/game" "$DOWNLOAD_DIR/$GAME_NAME/soltys-en-v1.0.zip"

if [ "$KEEP_INSTALLERS" == 'False' ]; then
rm -R "$DOWNLOAD_DIR/$GAME_NAME"
fi

#Soltys
