#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

get_mylib_distr 'Arena106Setup.zip' \
'http://static.elderscrolls.com/elderscrolls.com/assets/files/tes/extras/Arena106Setup.zip'

7z x -aoa -o"$INSTALL_DIR/$GAME_NAME/tmp" "$DOWNLOAD_DIR/$GAME_NAME/Arena106Setup.zip"
7z x -aoa -o"$INSTALL_DIR/$GAME_NAME/tmp" "$INSTALL_DIR/$GAME_NAME/tmp/Arena106.exe"
mv "$INSTALL_DIR/$GAME_NAME/tmp/ARENA" "$INSTALL_DIR/$GAME_NAME/game"
rm -R "$INSTALL_DIR/$GAME_NAME/tmp"

if [ "$KEEP_INSTALLERS" == 'False' ]; then
rm -R "$DOWNLOAD_DIR/$GAME_NAME"
fi

#The Elder Scrolls: Arena
