#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

ARCH=$(get_arch i)

if [ "$ARCH" == "amd64" ]; then
ARCHIVE='openttd-1.6.1-linux-generic-amd64.tar.xz'
get_mylib_distr "$ARCHIVE" \
'https://binaries.openttd.org/releases/1.6.1/openttd-1.6.1-linux-generic-amd64.tar.xz'
else
ARCHIVE='openttd-1.6.1-linux-generic-i686.tar.xz'
get_mylib_distr "$ARCHIVE" \
'https://binaries.openttd.org/releases/1.6.1/openttd-1.6.1-linux-generic-i686.tar.xz'
fi

tar xvfJ  "$DOWNLOAD_DIR/$GAME_NAME/$ARCHIVE" -C \
"$INSTALL_DIR/$GAME_NAME"
mv "$INSTALL_DIR/$GAME_NAME/openttd-"* "$INSTALL_DIR/$GAME_NAME/game"

if [ "$KEEP_INSTALLERS" == 'False' ]; then
rm -R "$DOWNLOAD_DIR/$GAME_NAME"
fi

#OpenTTD
