#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

get_mylib_distr 'spelunky_classic_hd_linux.7z' \
'https://github.com/yancharkin/SpelunkyClassicHD/releases/download/1.1.1/spelunky_classic_hd_linux.7z'

get_mylib_distr 'translations.zip' \
'https://github.com/yancharkin/SpelunkyClassicHDTranslations/archive/master.zip'

7z x -aoa -o"$INSTALL_DIR/$GAME_NAME/game" \
"$DOWNLOAD_DIR/$GAME_NAME/spelunky_classic_hd_linux.7z"

7z x -aoa -o"$INSTALL_DIR/$GAME_NAME/game/tmp" \
"$DOWNLOAD_DIR/$GAME_NAME/translations.zip"
cp -R "$INSTALL_DIR/$GAME_NAME/game/tmp/"*/* \
"$INSTALL_DIR/$GAME_NAME/game/assets/translations"
rm -R "$INSTALL_DIR/$GAME_NAME/game/tmp/"

if [ "$KEEP_INSTALLERS" == 'False' ]; then
rm -R "$DOWNLOAD_DIR/$GAME_NAME"
fi

#Spelunky Classic HD
