#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

get_mylib_distr 'Blackthorne-Setup.exe' \
'http://dist.blizzard.com/downloads/blackthorne/5e1a0ce1d84e3ee3005dd26181e14a2f/Blackthorne-Setup.exe'

7z x -aoa -o"$INSTALL_DIR/$GAME_NAME/tmp" \
"$DOWNLOAD_DIR/$GAME_NAME/Blackthorne-Setup.exe"
7z x -aoa -o"$INSTALL_DIR/$GAME_NAME/tmp" \
"$INSTALL_DIR/$GAME_NAME/tmp/_A48F2661F3CDB0B13C5AB4918FE2E91B"
mv "$INSTALL_DIR/$GAME_NAME/tmp/_C987F762EF304955BB86AB432FF6F847" \
"$INSTALL_DIR/$GAME_NAME/manual.pdf"
mkdir -p "$INSTALL_DIR/$GAME_NAME/game"
mv "$INSTALL_DIR/$GAME_NAME/tmp/_7770311E01264484BDC66FB81E4EF650" \
"$INSTALL_DIR/$GAME_NAME/game/BTHORNE.EXE"
mv "$INSTALL_DIR/$GAME_NAME/tmp/_126448A72F4442D39DCD600746EE09F7" \
"$INSTALL_DIR/$GAME_NAME/game/DATA.DAT"
rm -r "$INSTALL_DIR/$GAME_NAME/tmp/"

if [ "$KEEP_INSTALLERS" == 'False' ]; then
rm -R "$DOWNLOAD_DIR/$GAME_NAME"
fi

#Blackthorne
