#!/bin/bash

DOWNLOAD_DIR=$1
INSTALL_DIR=$2
KEEP_INSTALLERS=$4

if [ ! -e $DOWNLOAD_DIR'/katawa_shoujo' ]; then
	mkdir -p $DOWNLOAD_DIR'/katawa_shoujo'
	curl -L --globoff -o $DOWNLOAD_DIR'/katawa_shoujo/katawa_shoujo_1.3.1.tar.bz2' \
	'http://dl.katawa-shoujo.com/gold_1.3.1/[4ls]_katawa_shoujo_1.3.1-[linux-x86][18161880].tar.bz2'
fi

mkdir -p $INSTALL_DIR/'katawa_shoujo'
tar -xvf $DOWNLOAD_DIR'/katawa_shoujo/katawa_shoujo_1.3.1.tar.bz2' -C \
$INSTALL_DIR/'katawa_shoujo/'

mv $INSTALL_DIR/'katawa_shoujo/Katawa Shoujo-1.3.1-linux' \
$INSTALL_DIR/'katawa_shoujo/game'

if [ $KEEP_INSTALLERS == 'False' ]; then
	rm -R $DOWNLOAD_DIR'/katawa_shoujo'
fi

echo -e '#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
$DIR"/game/Katawa Shoujo.sh"' > $INSTALL_DIR'/katawa_shoujo/start.sh'
chmod +x $INSTALL_DIR'/katawa_shoujo/start.sh'

#Katawa Shoujo
