#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

get_mylib_distr 'drascula-1.0.zip' \
'http://scummvm.org/frs/extras/Drascula_%20The%20Vampire%20Strikes%20Back/drascula-1.0.zip'

get_mylib_distr 'drascula-audio-2.0.zip' \
'http://scummvm.org/frs/extras/Drascula_%20The%20Vampire%20Strikes%20Back/drascula-audio-2.0.zip'

7z x -aoa -o"$INSTALL_DIR/$GAME_NAME/game" "$DOWNLOAD_DIR/$GAME_NAME/drascula-1.0.zip" \
& proc_timer $! "Extracting drascula-1.0.zip"

7z x -aoa -o"$INSTALL_DIR/$GAME_NAME/game" "$DOWNLOAD_DIR/$GAME_NAME/drascula-audio-2.0.zip" \
& proc_timer $! "Extracting drascula-audio-2.0.zip"

if [ "$KEEP_INSTALLERS" == 'False' ]; then
rm -R "$DOWNLOAD_DIR/$GAME_NAME"
fi

#Drascula: The Vampire Strikes Back
