#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

get_mylib_distr 'digital-1.1.tar.bz2' \
'http://www.scoutshonour.com/lilyofthevalley/digital-1.1.tar.bz2'

mkdir -p "$INSTALL_DIR/$GAME_NAME"
tar -xvf "$DOWNLOAD_DIR/$GAME_NAME/digital-1.1.tar.bz2" -C "$INSTALL_DIR/$GAME_NAME/"

mv "$INSTALL_DIR/$GAME_NAME/Digital-linux-x86" "$INSTALL_DIR/$GAME_NAME/game"

if [ "$KEEP_INSTALLERS" == 'False' ]; then
rm -R "$DOWNLOAD_DIR/$GAME_NAME"
fi

#Digital: A Love Story
