#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

if [ ! -f "$DOWNLOAD_DIR/$GAME_NAME/katawa_shoujo_1.3.1.tar.bz2" ]; then
mkdir -p "$DOWNLOAD_DIR/$GAME_NAME"
curl -L --globoff -o "$DOWNLOAD_DIR/$GAME_NAME/katawa_shoujo_1.3.1.tar.bz2" \
'http://dl.katawa-shoujo.com/gold_1.3.1/[4ls]_katawa_shoujo_1.3.1-[linux-x86][18161880].tar.bz2'  \
& proc_timer $! "Downloading katawa_shoujo_1.3.1.tar.bz2"
fi

mkdir -p "$INSTALL_DIR/$GAME_NAME"
tar -xvf "$DOWNLOAD_DIR/$GAME_NAME/katawa_shoujo_1.3.1.tar.bz2" -C \
"$INSTALL_DIR/$GAME_NAME"
mv "$INSTALL_DIR/$GAME_NAME/Katawa Shoujo-1.3.1-linux" \
"$INSTALL_DIR/$GAME_NAME/game"

if [ "$KEEP_INSTALLERS" == 'False' ]; then
rm -R "$DOWNLOAD_DIR/$GAME_NAME"
fi

#Katawa Shoujo
