#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

INSTALL_DIR_WIN=$(echo Z:$INSTALL_DIR | sed -e 's=/=\\=g')

if [ ! -f "$DOWNLOAD_DIR/$GAME_NAME/"* ]; then
mkdir -p "$DOWNLOAD_DIR/$GAME_NAME"
humblebundle --username '_email_' --password '_password_' \
--platform windows --download 'ageofwonders' --path "$DOWNLOAD_DIR/$GAME_NAME/" \
& proc_timer $! "Downloading 'Age of Wonders'"
fi

mkdir -p "$DOWNLOAD_DIR/_distr"

if [ ! -f "$DOWNLOAD_DIR/_distr/iv5setup.exe" ]; then
curl -L -o "$DOWNLOAD_DIR/_distr/iv5setup.exe" \
'http://s3.amazonaws.com/moviecodec/files/iv5setup.exe'
fi

INSTALLER=$(ls "$DOWNLOAD_DIR/$GAME_NAME")

cp "$DOWNLOAD_DIR/$GAME_NAME/$INSTALLER" \
"$INSTALL_DIR/$GAME_NAME/"

mkdir -p "$INSTALL_DIR/$GAME_NAME/game"

if [ $WINE_PATH == "wine" ]; then
export WINELOADER="wine"
export WINEPREFIX="$HOME/.games_nebula/wine_prefix"
else
export WINE="$WINE_PATH/bin/wine"
export WINELOADER="$WINE_PATH/bin/wine"
export WINESERVER="$WINE_PATH/bin/wineserver"
export WINEDLLPATH="$WINE_PATH/lib"
export WINEPREFIX="$HOME/.games_nebula/wine_prefix"
fi

$WINELOADER "$INSTALL_DIR/$GAME_NAME/$INSTALLER" /NCRC /S /D=\
"$INSTALL_DIR_WIN\\$GAME_NAME\game" \
& proc_timer $! "Installing 'Age of Wonders'"

rm "$INSTALL_DIR/$GAME_NAME/$INSTALLER"

if [ $KEEP_INSTALLERS == 'False' ]; then
rm -R "$DOWNLOAD_DIR/$GAME_NAME"
fi

echo -e '#!/bin/bash
mkdir -p "$WINEPREFIX/drive_c/windows/system32"
cd "$DOWNLOAD_DIR/_distr"
7z x -otmp iv5setup.exe
cd tmp
unshield x data1.cab
cp Indeo_3_2_codec/ir32_32.dll "$WINEPREFIX/drive_c/windows/system32"
cd ..
rm -R tmp
$WINELOADER reg add "HKLM\Software\Microsoft\Windows NT\CurrentVersion\drivers.desc" \
/v "ir32_32.dll" /t REG_SZ /d "Indeo® Video R3.2" /f 
$WINELOADER reg add "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Drivers32" \
/v "vidc.iv32" /t REG_SZ /d "ir32_32.dll" /f
' > "$ADDITIONS_FILE" && chmod +x "$ADDITIONS_FILE"

#Age of Wonders
