#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

if [ ! -f "$DOWNLOAD_DIR/$GAME_NAME/battle_for_wesnoth.7z" ]; then
mkdir -p "$DOWNLOAD_DIR/$GAME_NAME"
megadl 'https://mega.nz/#!q94hxKYQ!QoxSGiwweJi8JYM1V7vi8-dYPKbfHCJ0BqXnlz6UH_I' \
--path "$DOWNLOAD_DIR/$GAME_NAME/" \
& proc_timer $! "Downloading 'The Battle for Wesnoth'"
fi

7z x -o"$INSTALL_DIR/$GAME_NAME/game" "$DOWNLOAD_DIR/$GAME_NAME/battle_for_wesnoth.7z" \
& proc_timer $! "Installing 'The Battle for Wesnoth'"

if [ $KEEP_INSTALLERS == 'False' ]; then
rm -R "$DOWNLOAD_DIR/$GAME_NAME"
fi

#The Battle for Wesnoth
