#!/bin/bash

source "${NEBULA_DIR}/scripts/shell_functions.sh"

VERSION=$(python "${NEBULA_DIR}/dialogs.py" list "i386, i386-yyc, HTML5 i386, HTML5 amd64")

if [[ "${VERSION}" == *"i386"* ]] && [[ "${VERSION}" != *"HTML5"* ]]; then
    echo "i386"
    DIST_NAME="spelunky_classic_hd-linux-${VERSION}.tar.gz"
    DOWNLOAD_URL=$(curl -s 'https://api.github.com/repos/yancharkin/SpelunkyClassicHD/releases/latest' | grep browser_download_url | grep linux-${VERSION}.tar.gz| cut -d '"' -f 4)
    get_mylib_distr "${DIST_NAME}" "${DOWNLOAD_URL}"
    mkdir -p "${INSTALL_DIR}/${GAME_NAME}/game"
    tar -xf "${DOWNLOAD_DIR}/${GAME_NAME}/${DIST_NAME}" -C "${INSTALL_DIR}/${GAME_NAME}/game"
else
    if [[ "${VERSION}" == *"amd64"* ]]; then
        DIST_NAME="spelunky_classic_hd_html5-linux-x86_64.AppImage"
        DOWNLOAD_URL=$(curl -s 'https://api.github.com/repos/yancharkin/SpelunkyClassicHDhtml5/releases/latest' | grep browser_download_url | grep linux-x86_64.AppImage | cut -d '"' -f 4)
    elif [[ "${VERSION}" == *"i386"* ]]; then
        DIST_NAME="spelunky_classic_hd_html5-linux-i386.AppImage"
        DOWNLOAD_URL=$(curl -s 'https://api.github.com/repos/yancharkin/SpelunkyClassicHDhtml5/releases/latest' | grep browser_download_url | grep linux-i386.AppImage | cut -d '"' -f 4)
    fi
    get_mylib_distr "${DIST_NAME}" "${DOWNLOAD_URL}"
    mkdir -p "${INSTALL_DIR}/${GAME_NAME}/game"
    cp "${DOWNLOAD_DIR}/${GAME_NAME}/${DIST_NAME}" "${INSTALL_DIR}/${GAME_NAME}/game/"
    {
        echo "#!/bin/bash"
        echo 'DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"'
        echo '${DIR}/'"${DIST_NAME}"
    } > "${INSTALL_DIR}/${GAME_NAME}/game/spelunky"
    chmod +x "${INSTALL_DIR}/${GAME_NAME}/game/spelunky"
fi

if [ "${KEEP_INSTALLERS}" == 'False' ]; then
    rm -R "${DOWNLOAD_DIR}/${GAME_NAME}"
fi

#Spelunky Classic HD
