#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

get_mylib_distr 'sfinx-en-v1.1.zip' \
'http://scummvm.org/frs/extras/Sfinx/sfinx-en-v1.1.zip'

7z x -o"$INSTALL_DIR/$GAME_NAME" "$DOWNLOAD_DIR/$GAME_NAME/sfinx-en-v1.1.zip"

mv "$INSTALL_DIR/$GAME_NAME/sfinx-en-v1.1" "$INSTALL_DIR/$GAME_NAME/game"

if [ "$KEEP_INSTALLERS" == 'False' ]; then
rm -R "$DOWNLOAD_DIR/$GAME_NAME"
fi

#Sfinx
